version: '3.8'

services:
  backend:
    build: ./backend
    container_name: lms-backend
    ports:
      - "5000:5000"
    volumes:
      - lms-uploads:/app/uploads
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: lms-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

volumes:
  lms-uploads:
